name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  cupertino_icons: null
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_assets:
  assets_path: assets/svg/
  output_path: lib/core/utils/assets
  filename: app_assets.dart
  field_prefix: