name: e_commerce_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.11
  cupertino_icons: null
  dio: ^5.4.3+1
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  get_it: ^7.7.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  svg_flutter: ^0.0.1
  retrofit_generator: ^8.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/
    - assets/icons/
    - assets/img/
  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800

flutter_assets:
  assets_path: assets/img/
  output_path: lib/core/utils/assets/
  filename: app_images.dart
  field_prefix: ""
flutter_intl:
  enabled: true
