name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  cupertino_icons: null
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.3
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/
    - assets/img/
  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
flutter_assets:
  assets_path: assets/img/
  output_path: lib/core/utils/assets/
  filename: app_images.dart
  field_prefix: ""
